build:
  version: "1.0"

accounts:
  message: "Welcome to  SBI accounts related PROD APIs "
  contactDetails:
    name: "SHankaR - Product Owner"
    email: "shankar@sbi.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345