build:
  version: "3.0"

accounts:
  message: "Welcome to  SBI accounts related local APIs "
  contactDetails:
    name: "SHankaR - Developer"
    email: "shankar@sbi.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345