build:
  version: "3.0"

cards:
  message: "Welcome to  SBI Cards related Local APIs "
  contactDetails:
    name: "SHankaR - QA-Lead"
    email: "shankar@sbi.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345