build:
  version: "3.0"

loans:
  message: "Welcome to  SBI Loans related Local APIs "
  contactDetails:
    name: "SHankaR - Product Owner"
    email: "shankar@sbi.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345